### ISSUE TITLE
Cannot make it work

### ISSUE THREAD

**Issue by lucasgonzalez** [SummaSolutions/cart-magento2#25]
Hi,

I am trying to use this in magento 2.1 and I can't.

The first problem I see is that when I click on place order, I get an instant error. For what I can see the error is because the js:

`window.checkoutConfig.payment.iframe.timeoutTime[this.getCode()]`

returns undefined because there is no timeoutTime with the code mercadopago_custom.

I added that variable in the file:
MercadoPago/Core/Model/CustomConfigProvider.php

and now I do not get that error but others.

So I do not know if I am configuring something wrong, or if this module is not functional yet.

Thanks.

**Comment by imasson** [comment]
Hi @lucasgonzalez.
Git repository has been updated with changes related to new Magento2 version.

Please update your files from [https://github.com/SummaSolutions/cart-magento2/tree/develop](https://github.com/SummaSolutions/cart-magento2/tree/develop).

Thanks,
Ivan Masson.
