### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by dmacros** [SummaSolutions/cart-magento2#31]
Hi, after run bin/magento setup:upgradeconsole asked me to re run magento compile. I do (magento setup:di:compile) from then the application give me a lots of 404 for JS and CSS.

**Comment by imasson** [comment]
Hi @dmacros, you also need to deploy static content. The commands order is:
bin/magento setup:upgrade
bin/magento setup:di:compile
bin/magento setup:static-content:deploy

Let us know if you solve the issue.
Ivan Masson.
